"""export quantized weights as readmemh hex files and scales.vh.
reads data/model_int8.pt, writes weights/*.hex and weights/scales.vh."""
from __future__ import annotations

import argparse
from pathlib import Path

import torch


SCRIPT_DIR  = Path(__file__).resolve().parent
DATA_DIR    = SCRIPT_DIR.parent / "data"
WEIGHTS_DIR = SCRIPT_DIR.parent / "weights"


def int8_to_hex(v: int)  -> str: return f"{v & 0xFF:02x}"
def int32_to_hex(v: int) -> str: return f"{v & 0xFFFFFFFF:08x}"


def write_int8_hex(path: Path, t: torch.Tensor, header: str) -> None:
    flat = t.flatten().tolist()
    with open(path, "w") as f:
        f.write(f"// {header}\n")
        f.write(f"// {len(flat)} int8 values, two's complement, one per line\n")
        for v in flat:
            f.write(int8_to_hex(int(v)) + "\n")


def write_int32_hex(path: Path, t: torch.Tensor, header: str) -> None:
    flat = t.flatten().tolist()
    with open(path, "w") as f:
        f.write(f"// {header}\n")
        f.write(f"// {len(flat)} int32 values, two's complement, one per line\n")
        for v in flat:
            f.write(int32_to_hex(int(v)) + "\n")


def main() -> int:
    p = argparse.ArgumentParser()
    p.add_argument("--in-pt",   type=Path, default=DATA_DIR / "model_int8.pt")
    p.add_argument("--out-dir", type=Path, default=WEIGHTS_DIR)
    args = p.parse_args()

    state = torch.load(args.in_pt, map_location="cpu", weights_only=True)
    args.out_dir.mkdir(parents=True, exist_ok=True)

    # conv layers
    write_int8_hex (args.out_dir / "conv1_w.hex", state["w1_q"],
                    "conv1 weights, shape=(8,1,3,3),   order=(oc,ic,kh,kw)")
    write_int32_hex(args.out_dir / "conv1_b.hex", state["b1_q"],
                    "conv1 bias,  shape=(8,)")
    write_int8_hex (args.out_dir / "conv2_w.hex", state["w2_q"],
                    "conv2 weights, shape=(16,8,3,3),  order=(oc,ic,kh,kw)")
    write_int32_hex(args.out_dir / "conv2_b.hex", state["b2_q"],
                    "conv2 bias,  shape=(16,)")
    write_int8_hex (args.out_dir / "conv3_w.hex", state["w3_q"],
                    "conv3 weights, shape=(16,16,3,3), order=(oc,ic,kh,kw)")
    write_int32_hex(args.out_dir / "conv3_b.hex", state["b3_q"],
                    "conv3 bias,  shape=(16,)")

    # fc layer
    write_int8_hex (args.out_dir / "fc_w.hex", state["wfc_q"],
                    "fc weights, shape=(5,144), order=(out_feat, in_feat); "
                    "out 0=conf logit, 1=cx, 2=cy, 3=w, 4=h")
    write_int32_hex(args.out_dir / "fc_b.hex", state["bfc_q"],
                    "fc bias, shape=(5,)")

    # scales.vh
    scales_path = args.out_dir / "scales.vh"
    with open(scales_path, "w") as f:
        f.write("// auto-generated by scripts/export_weights.py - do not edit\n")
        f.write("`ifndef SCALES_VH\n")
        f.write("`define SCALES_VH\n")
        f.write("// Per-conv requantization right-shifts\n")
        f.write(f"`define CONV1_SHIFT      {int(state['shift1'])}\n")
        f.write(f"`define CONV2_SHIFT      {int(state['shift2'])}\n")
        f.write(f"`define CONV3_SHIFT      {int(state['shift3'])}\n")
        f.write("// FC output dequantization shift: bbox_pixels = fc_int32 >>> FC_OUT_SHIFT\n")
        f.write(f"`define FC_OUT_SHIFT     {int(state['fc_out_shift'])}\n")
        f.write("// Activation / weight scale exponents (info only)\n")
        f.write(f"`define INPUT_SCALE_EXP  {int(state['sa_in'])}\n")
        f.write(f"`define ACT1_SCALE_EXP   {int(state['sa1'])}\n")
        f.write(f"`define ACT2_SCALE_EXP   {int(state['sa2'])}\n")
        f.write(f"`define ACT3_SCALE_EXP   {int(state['sa3'])}\n")
        f.write(f"`define W1_SCALE_EXP     {int(state['sw1'])}\n")
        f.write(f"`define W2_SCALE_EXP     {int(state['sw2'])}\n")
        f.write(f"`define W3_SCALE_EXP     {int(state['sw3'])}\n")
        f.write(f"`define WFC_SCALE_EXP    {int(state['swfc'])}\n")
        f.write("`endif // SCALES_VH\n")

    print(f"wrote weight hex files and scales.vh to {args.out_dir}")
    print(f"  FC_OUT_SHIFT = {int(state['fc_out_shift'])}  "
          "(use this as the BBOX_SHIFT parameter in detector_top)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
