// auto-generated by scripts/export_weights.py — do not edit
// Requantization right-shift bits per conv layer
`define CONV1_SHIFT 10
`define CONV2_SHIFT 8
`define CONV3_SHIFT 10
// Activation scale exponents (info only; quantization rep = int_value / 2^scale)
`define INPUT_SCALE_EXP 7
`define ACT1_SCALE_EXP  5
`define ACT2_SCALE_EXP  5
`define ACT3_SCALE_EXP  3
// Weight scale exponents
`define W1_SCALE_EXP   8
`define W2_SCALE_EXP   8
`define W3_SCALE_EXP   8
`define WFC_SCALE_EXP  8
